### ISSUE TITLE
Deleting files

### ISSUE THREAD

**Issue by uLearnIT** [koleeit/download-detective#2]
Once I have a list of say, all installers (which is quite slow too generate), the only two options I have is to Delete All (probably never want to do that) or click one to locate it and delete. I want to be able to mark a few of the files and delete them or move/copy.

**Comment by yahoai** [comment]
@uLearnIT 

Hello. That feature is on our development list. We will notify you once the development is complete.

If the list generation is slow, letting us know the capacity of the download folder and the number of files will help us improve the function.

**Comment by uLearnIT** [comment]
Thank you. The Downloads folder is 5.89GB, 1197 files. Any listing takes about 9 seconds to generate.

**Comment by yahoai** [comment]
Hello, @uLearnIT 

A new feature has been added in version 0.3.0. Now, you can select files to delete or move them within the File Manager View.

Additionally, I am looking into performance issues but have not been able to reproduce them yet. I will keep investigating and will update you once any improvements are made.

I will close this issue now.

Thank you.

![Frame 31](https://github.com/koleeit/download-detective/assets/2654930/ae3d45e4-9fad-4ed2-a26b-504cea54db8f)
